config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :events, only: [:index, :new, :create, :edit, :update, :destroy]
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user

  validates :name, :date, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  before_action :configure_permitted_parameters, if: :devise_controller?

  def current_user
    UserDecorator.decorate(super) unless super.nil?
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:name]
    devise_parameter_sanitizer.for(:account_update) << [:name]
  end

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  def index
    @events = current_user.events
    respond_to do |format|
      format.html { render 'events/index'}
      format.json { render json: ActiveModel::ArraySerializer.new(@events, each_serializer: EventSerializer) }
    end
  end

  def new
    @event_new_form = EventNewForm.new
  end

  def create
    @event_new_form      = EventNewForm.new(event_new_form_params)
    @event_new_form.user = current_user.object
    if @event_new_form.save
      redirect_to events_path, notice: "event '#{@event_new_form.name}' was created"
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
    authorize @event
  end

  def update
    @event = Event.find(params[:id])
    authorize @event
    if @event.update(event_edit_params)
      redirect_to events_path, notice: "event '#{@event.name}' was updated"
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    authorize @event
    @event.destroy
    redirect_to events_path, notice: "event '#{@event.name}' was deleted"
  end

  private

  def event_new_form_params
    params.require(:event_new_form).permit(:name, :date, :period, :end_date)
  end

  def event_edit_params
    params.require(:event).permit(:name, :date)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: 'alert-success', error: 'alert-danger', alert: 'alert-warning', notice: 'alert-info' }[flash_type.to_sym] || flash_type.to_s
  end
  
end

app/views/events/edit.slim
h2
  | Edit event
= bootstrap_form_for @event do |f|
  = f.text_field :name
  = f.date_field :date
  = f.submit

h3
  | Delete Event
= button_to 'Delete Event', event_path(@event), data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-default'

app/views/events/index.slim
#calendar

app/views/events/new.slim
h2
  | New event
= bootstrap_form_for @event_new_form, url: events_path do |f|
  = f.text_field :name
  = f.date_field :date
  = f.select     :period, %w(no_repeat daily weekly monthly yearly)
  = f.date_field :end_date
  = f.submit 'Create Event'

app/views/home/index.slim
h1 Hello Flatstack!

app/views/layouts/_flash.slim
- flash.each do |type, msg|
 div[class=['alert', bootstrap_class_for(type), 'alert-dismissible'] role='alert']
   button.close[type='button' data-dismiss='alert' aria-label='Close']
     span[aria-hidden='true']
       | ×
   = msg

app/views/layouts/_navbar.slim
nav.navbar.navbar-default
  .container-fluid
    ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        li
          = link_to 'events', events_path
        li
          = link_to 'new event', new_event_path
        li.dropdown
          a.dropdown-toggle[href='#' data-toggle='dropdown' role='button' aria-haspopup='true' aria-expanded='false']
            = current_user.full_name
            span.caret
          ul.dropdown-menu
            li
              = link_to 'Edit profile', edit_user_registration_path
            li.divider[role='separator']
            li
              = link_to 'Exit', destroy_user_session_path, method: :delete
      - else
        li
          = link_to 'Log in', user_session_path
        li
          = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.slim
doctype html
html
  head
    title
      | FlatstackTest
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    meta[name='viewport' content='width=device-width, initial-scale=1']
  body
    .container
      = render 'layouts/navbar'
      = render 'layouts/flash'
      = yield